<?php

namespace app\modules\admin\components;

use yii\grid\GridView as GridViewMain;
use yii\helpers\Html;

class GridView extends GridViewMain
{
    public $title;
    public $buttons;

    public $dataColumnClass = 'app\modules\admin\components\DataColumn';
    public $tableOptions = ['class' => 'table table-hover'];

    public $pager = [
        'options' => [
            'class' => 'pagination pagination-sm no-margin pull-right',
        ],
    ];

    public $footerRowOptions = ['class' => 'box-tools'];

    public function init()
    {
        $this->initLayout();
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function initLayout()
    {
        $this->layout = '<div class="box box-primary">' .
            '<div class="box-header with-border">{title}<div class="box-tools">{buttons}</div></div>' .
            '<div class="box-body table-responsive no-padding">{items}</div>' .
            '<div class="box-footer clearfix"><div class="col-sm-5">{summary}</div><div class="col-sm-7">{pager}</div></div>' .
            '</div>';
    }

    public function renderSection($name)
    {
        if ($name == '{title}')
            return $this->renderTitle();

        if ($name == '{buttons}')
            return $this->renderButtons();

        return parent::renderSection($name);
    }

    public function renderTitle()
    {
        if ($this->title)
            return Html::tag('h3', $this->title, ['class' => 'box-title']);
    }

    public function renderButtons()
    {
        $result = '';
        if (isset($this->buttons) && (is_array($this->buttons))) {
            foreach ($this->buttons as $btn) {
                $result .= $btn;
            }
        }
        return $result;
    }
}