<?php
namespace app\widgets\ModalWindowWidget;

use app\models\ModalWindow;
use yii\base\Widget;
use Yii;
use yii\helpers\Url;
use yii\web\View;

class ModalWindowWidget extends Widget
{
	public function run()
	{
		$modal_window = ModalWindow::find()
			->where(['<=', 'date_from', time()])
			->andWhere(['>=', 'date_to', time()])
			->one();
		$session = Yii::$app->session;

		if ( !$modal_window ) {
			return '';
		}
		$id_window = $session->get('modal_window');
		if ( ($modal_window->type_show == ModalWindow::TYPE_ONE)
			&& ($id_window == $modal_window->id)  ) {
			return '';
		}
		$url = Url::to(['/site/content-window','id'=>$modal_window->id]);
		$session->set('modal_window',$modal_window->id);
		$script = <<< JS
$.post("$url",{},function(data){
    if (data.status) {
        showModal(data.title, data.content, '');
    }
});
JS;
		$view = $this->getView();
		$view->registerJs($script,View::POS_READY);
		parent::run(); // TODO: Change the autogenerated stub
	}
}