<?php
namespace app\widgets\MainServices;
use app\models\Menu;
use yii\base\Widget;

class MainServices extends Widget
{
    public function run()
    {
        $menu = Menu::find()->where(['category_id' => 4])->all();
        if ($menu) {
            $services = [
                ['img' => '/uploads/menu_images/1.jpg','name' => 'Родильное отделение', 'link' => '#'],
                ['img' => '/uploads/menu_images/2.jpg','name' => 'Многопрофильный медицинский центр', 'link' => '#'],
                ['img' => '/uploads/menu_images/3.jpg','name' => 'Стоматология', 'link' => '#'],
                ['img' => '/uploads/menu_images/4.jpg','name' => 'Детский центр', 'link' => '#'],
                ['img' => '/uploads/menu_images/5.jpg','name' => 'Помощь на дому', 'link' => '#'],
                ['img' => '/uploads/menu_images/6.jpg','name' => 'Вопросы и ответы', 'link' => '#'],
            ];
            foreach ($menu as $key => $menu_point) {
                $services[$key]['name'] = $menu_point->name;
                $services[$key]['link'] = $menu_point->getRealUrl();
            }

            return $this->render('index',['services' => $services]);
        }
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}