<?php
namespace app\widgets\SliderWidget;

use app\helpers\Formats;
use yii\base\Widget;
use app\models\Sliders;
use app\widgets\SliderWidget\assets\SlickAssets;

class SliderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
    	$depart = !empty(\Yii::$app->params['depart'])?\Yii::$app->params['depart']:null;

        $slides = Sliders::find()
	        ->where([
		        'depart' => $depart,
	        ])
	        ->orderBy([
	            'position' => SORT_ASC,
	        ])
	        ->all();
        if ($slides) {
        	$view = $this->view;
	        SlickAssets::register($view);
	        $id_slider = 'main_'.Formats::random();

	        $js = <<<JS
let slider = $('#$id_slider');
if (slider.length > 0) {
    console.log('Init slider');
    slider.slick({dots: true});
}
JS;
            $view->registerJs($js, $view::POS_READY, 'counter-reg');

            return $this->render('index',[
            	'slides' => $slides,
	            'id_slider' => $id_slider,
            ]);
        }
    }
}